services:
  apps:
    build: ./apps
    ports:
      - "10000:3000"
    restart: always
    env_file: ./apps/.env
    volumes:
      - backup-simple: ./apps
volumes:
  backup-simple:
    external: true
